### PR TITLE
Job annotations

### LINKED ISSUE #6: Option to add Job Annotation
There should be an option (or set of options) to [configure the job](https://docs.saucelabs.com/reference/test-configuration/#job-annotation) (such as name, build an tags). It would help with CI builds and it would generate badges for the projects.

### PR DESCRIPTION
**Pull request by fearphage**
Added the ability to annotate jobs in sauce labs. This fixes #6.

As I was changing code, I added tests to ensure I didn't break anything along the way.

### CODE REVIEW

**Comment by fearphage** [comment]
Here's sample usage:

## wct.conf.js

``` javascript
module.exports = {
  plugins: {
    sauce: {
      browsers: [
        'Linux/chrome',
        'OS X 10.9/safari@7',
        'Windows 7/internet explorer@10',
        'Windows 8.1/internet explorer@11'
      ],
      disabled: true,
      build: 31337,
      name: 'name to display in sauce',
      tags: ['integration', 'stage']
    }
  }
};
```

**Comment by fearphage** [comment]
@nevir Bump.

**Comment by nevir** [comment]
Looks good, thanks!

**Comment by fearphage** [comment]
It was my pleasure. Can you push this upgrade through to [web-component-tester](https://github.com/Polymer/web-component-tester)?

**Comment by nevir** [comment]
WCT should pick it up if you npm install it again; but yeah, I'll bump the dependency constraints w/ the next release of WCT

**Comment by fearphage** [comment]
I don't believe you pushed to `npm`. I just did `npm install wct-sauce@latest` and still came up with `1.2.0`. Thanks for the work.

**Comment by fearphage** [comment]
`1.3.0` is not published... just fyi.

``` shell
➜  ui git:(reverse-dropdown) ✗ npm view wct-sauce versions

[ '1.0.2',
  '1.0.3',
  '1.1.0',
  '1.2.0' ]
```

**Comment by nevir** [comment]
Ack, fixed

**Pull request merged**
