### PR TITLE
Take advantage of Travis CI's sauce connect tunnel when available.

### PR DESCRIPTION
**Pull request by jyasskin**

### CODE REVIEW

**Comment by dfreedm** [comment]
LGTM!

**Comment by dfreedm** [comment]
Ugh, have to revert for now. This _requires_ that travis start the sauce tunnel with the `sauce_connect` addon, as the `TRAVIS_BUILD_NUMBER` variable is always set, regardless of the `sauce_connect` addon

**Comment by jyasskin** [comment]
Argh, sorry. Do you want to file the Travis CI feature request, or should I?

**Comment by dfreedm** [comment]
FWIW, I worked around this in `1.8.2` by checking if the sauce connect log file exists.
I'll send them a feature request for better detection of addons.

**Comment by jyasskin** [comment]
Thanks!

**Pull request merged**
